<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522081506 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE club (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B8EE3872B03A8386 ON club (created_by_id)');
        $this->addSql('CREATE INDEX IDX_B8EE3872896DBBDE ON club (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_B8EE3872C76F1F52 ON club (deleted_by_id)');
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firste_name VARCHAR(255) NOT NULL, last_name VARCHAR(255) NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, club_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A65DF2AB4E5 ON player (club_id_id)');
        $this->addSql('CREATE INDEX IDX_98197A65B03A8386 ON player (created_by_id)');
        $this->addSql('CREATE INDEX IDX_98197A65896DBBDE ON player (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_98197A65C76F1F52 ON player (deleted_by_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, is_verified BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE wellness_questions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, fatigue INT DEFAULT NULL, sleep INT DEFAULT NULL, stress INT DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, player_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15FA1107C036E511 ON wellness_questions (player_id_id)');
        $this->addSql('CREATE INDEX IDX_15FA1107B03A8386 ON wellness_questions (created_by_id)');
        $this->addSql('CREATE INDEX IDX_15FA1107896DBBDE ON wellness_questions (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_15FA1107C76F1F52 ON wellness_questions (deleted_by_id)');
        $this->addSql('CREATE TABLE workload (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duration INT DEFAULT NULL, total_distance INT DEFAULT NULL, max_speed DOUBLE PRECISION DEFAULT NULL, acceleration INT DEFAULT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_deleted BOOLEAN DEFAULT false NOT NULL, player_id_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT NOT NULL, deleted_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1203AA7BC036E511 ON workload (player_id_id)');
        $this->addSql('CREATE INDEX IDX_1203AA7BB03A8386 ON workload (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1203AA7B896DBBDE ON workload (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_1203AA7BC76F1F52 ON workload (deleted_by_id)');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE3872B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE3872896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE3872C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65DF2AB4E5 FOREIGN KEY (club_id_id) REFERENCES club (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wellness_questions ADD CONSTRAINT FK_15FA1107C036E511 FOREIGN KEY (player_id_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wellness_questions ADD CONSTRAINT FK_15FA1107B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wellness_questions ADD CONSTRAINT FK_15FA1107896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE wellness_questions ADD CONSTRAINT FK_15FA1107C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workload ADD CONSTRAINT FK_1203AA7BC036E511 FOREIGN KEY (player_id_id) REFERENCES player (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workload ADD CONSTRAINT FK_1203AA7BB03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workload ADD CONSTRAINT FK_1203AA7B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE workload ADD CONSTRAINT FK_1203AA7BC76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE club DROP CONSTRAINT FK_B8EE3872B03A8386');
        $this->addSql('ALTER TABLE club DROP CONSTRAINT FK_B8EE3872896DBBDE');
        $this->addSql('ALTER TABLE club DROP CONSTRAINT FK_B8EE3872C76F1F52');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65DF2AB4E5');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65B03A8386');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65896DBBDE');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65C76F1F52');
        $this->addSql('ALTER TABLE wellness_questions DROP CONSTRAINT FK_15FA1107C036E511');
        $this->addSql('ALTER TABLE wellness_questions DROP CONSTRAINT FK_15FA1107B03A8386');
        $this->addSql('ALTER TABLE wellness_questions DROP CONSTRAINT FK_15FA1107896DBBDE');
        $this->addSql('ALTER TABLE wellness_questions DROP CONSTRAINT FK_15FA1107C76F1F52');
        $this->addSql('ALTER TABLE workload DROP CONSTRAINT FK_1203AA7BC036E511');
        $this->addSql('ALTER TABLE workload DROP CONSTRAINT FK_1203AA7BB03A8386');
        $this->addSql('ALTER TABLE workload DROP CONSTRAINT FK_1203AA7B896DBBDE');
        $this->addSql('ALTER TABLE workload DROP CONSTRAINT FK_1203AA7BC76F1F52');
        $this->addSql('DROP TABLE club');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE wellness_questions');
        $this->addSql('DROP TABLE workload');
    }
}
